### ISSUE TITLE
Filters need reload per view change

### ISSUE THREAD

**Issue by Mariusthvdb** [Mariusthvdb/custom-attributes#33] opened 2023-12-14 20:28 UTC
_Originally posted by @elchininet in https://github.com/Mariusthvdb/custom-attributes/issues/32#issuecomment-1856525489_
            
what ever  I do, even minimized to
```
filter_attributes:

  by_entity_id:

    sensor.cpu_speed:
      - brand
 ```

I constantly need to reload the view to get it working. Somehow someting must have changed during our transition to 1.0.0, because before it was working beautifully, and all filters were applied and sticky (albeit after initial reload per dashboard, as described in the readme)

I did check and downgraded to that version just now, but it has the same issue, so its  not that.

The only real change I my config is a Supervisor update to  https://github.com/home-assistant/supervisor/releases/tag/2023.12.0 but I cant see any related changes there.

Issue for discussion here..

**Comment by elchininet** [comment] 2023-12-14 20:34
>Somehow someting must have changed during our transition to 1.0.0

It has been in version `1.0.0` since the beginning, we have not released it yet so the version has not changed.

I will do something, I will prepare a special branch with a code with multiple `console.log` so you can check the messages in the console and it will be easy to debug what is failing in your environment.

**Comment by elchininet** [comment] 2023-12-14 20:46
Try this: https://github.com/Mariusthvdb/custom-attributes/pull/34

When the dashboard is loaded (or when you abandon it and return) you should get this:

<img width="437" alt="image" src="https://github.com/Mariusthvdb/custom-attributes/assets/3728220/016a7305-599f-4d80-b20f-e1673127ee2d">

Then when you open a dialog you should get this:

<img width="524" alt="image" src="https://github.com/Mariusthvdb/custom-attributes/assets/3728220/b6f17f30-49a6-4bd8-be33-60d2a370e2af">

Let‘s see what you get on each case and we can determine in which step it is failing.

**Comment by elchininet** [comment] 2023-12-14 20:52
By the way, it would be good at the end to have this is the code.
Imagine that we add an option:

```yaml
custom_attributes:
  debug: true
```

And all those `console.logs` appear, so if someone is having an issue is very easy to debug. (Even it would be good for `kiosk-mode`).

**Comment by Mariusthvdb** [comment] 2023-12-14 20:54
yes, thats it, it loads a view, even works( and all filters are printed, but navigating to another show this:

<img width="418" alt="Scherm­afbeelding 2023-12-14 om 21 51 48" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/93842f8d-54d4-46b3-a587-edd323120fa2">

seems empty to me...

next opening a more-info there:

<img width="946" alt="Scherm­afbeelding 2023-12-14 om 21 52 51" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/13e67162-9cd7-457b-a192-e8d4b689296b">

again empty filters. (and they are all shown)

then after a reload of that view:

<img width="903" alt="Scherm­afbeelding 2023-12-14 om 21 53 54" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/b8f025d6-7327-49c9-9d90-d1ef042f9df5">

th filters are correctly printed, and applied

**Comment by elchininet** [comment] 2023-12-14 20:58
When you say "view" you mean another tab in the same dashboard?

Changing views should not trigger the configuration load.

**Comment by Mariusthvdb** [comment] 2023-12-14 21:09
correct, I moved from a 'subview' to the view/dashboard containing that subview, so technically thats another dashboard.

the behavior is consistent though

move to another view inside the same dash to a device_tracker.google_*:

<img width="764" alt="Scherm­afbeelding 2023-12-14 om 22 07 09" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/e8e84609-ac03-442d-9ba2-95cb864acf14">

no filters seen.

after a reload of that same view:

<img width="901" alt="Scherm­afbeelding 2023-12-14 om 22 08 07" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/a8397dcd-bb49-4854-bcbb-7ee5b5c40b5b">

theyre picked up and applied

**Comment by elchininet** [comment] 2023-12-14 21:17
Just to make sure we are talking about the same, does it happen when you change in `1` or in `2`? Because if it is `2` it is expected.

![image](https://github.com/Mariusthvdb/custom-attributes/assets/3728220/a4e4e37f-8606-424a-8ea0-d4e81bfe47e0)

**Comment by Mariusthvdb** [comment] 2023-12-14 21:32
Before it worked just fine when changing in 1 (the views)

Why do you think that is expected

When changing the dashboards (left side menu, 2) it happens all the time

**Comment by elchininet** [comment] 2023-12-14 21:41
I am updating just to see if I can reproduce the same as you, changing views (1) should not load the configuration, views are not dashboards, they all belong to the same dashboard.

But changing in 2 is expected that you end-up with an empty config just because you have the configuration added to one dashboard, loading another dashboard will try to load the config in that dashboard, this is taken from `kiosk-mode`:

![Screenshot_2023-12-14-22-36-28-42_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/Mariusthvdb/custom-attributes/assets/3728220/d400d0af-77d0-4d93-a183-fa06f421eaa1)

**Comment by elchininet** [comment] 2023-12-14 21:52
No, the issue is not Home Assistant Core, I have updated to `2023.12.2` and I got the same as before. Changing in views do not tries to load the configuration again. When you change your views how does your URL behave? This is an example from mine:

* lovelace/home
* lovelace/muziek
* lovelace/alarmen

In your case it remains in the same dashboard (in my case `lovelace`) or does it change to another one?

**Comment by Mariusthvdb** [comment] 2023-12-14 22:06
yes ofc my views change, they're all perfect fine and organized....
an, they have changed.

I misunderstood what you said earlier, about expected. I thought you said it was expected that the filters didnt work. Which ofc is not expected.

But I see what you mean now, so there's no issue there.

And yes, ofc I have configured the custom_attributes on all of my dashboards.

these are my Dashboards:

<img width="570" alt="Scherm­afbeelding 2023-12-14 om 23 02 44" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/3d2f350d-a9cb-43e0-8891-adb6227acd83">

and for each dashboard in their .yaml file I have this:

```
title: Ha Main

button_card_templates: !include_dir_merge_named ../button_card_templates
decluttering_templates: !include_dir_named ../decluttering_templates
kiosk_mode: !include ../kiosk-mode/kiosk-mode.yaml
custom_attributes: !include ../custom_attributes/custom_attributes.yaml

views:
  - !include ui-overzicht/view_overzicht_Welkom.yaml         #0
  - !include ui-overzicht/view_overzicht_Plattegrond.yaml    #1
  - !include ui-overzicht/view_overzicht_Schakelaars.yaml    #2
  - !include ui-overzicht/view_overzicht_Verlichting.yaml    #3
  - !include ui-overzicht/view_overzicht_Rolluiken.yaml      #4
  - !include ui-overzicht/view_overzicht_Intercom.yaml       #5
  - !include ui-overzicht/view_overzicht_Weer.yaml           #6
  - !include ui-overzicht/view_overzicht_Kalender.yaml       #7
  - !include ui-overzicht/view_overzicht_Media_spelers.yaml  #8
```

What I havent tasted yet, is loading the resource in frontend like:
```
frontend:
  themes: !include_dir_merge_named /config/dashboard/themes

  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
```

this seems to work beter for card-mod too, so Ill give it a try, it makes the resource load before anything else.

l'll make that:
```
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /local/resources/custom-attributes/custom-attibutes.js
```

**Comment by Mariusthvdb** [comment] 2023-12-14 22:09
btw, do you speak Dutch ??

**Comment by Mariusthvdb** [comment] 2023-12-14 22:13
<img width="1430" alt="Scherm­afbeelding 2023-12-14 om 23 12 30" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/39ba6db0-c9f8-4b5d-a89b-79db74a01db9">

**Comment by elchininet** [comment] 2023-12-14 22:14
>And yes, ofc I have configured the custom_attributes on all of my dashboards.

I don‘t see anything weird there, it seems to be OK.

>What I havent tasted yet, is loading the resource in frontend like:

That is the way that I use in [kiosk-mode](https://github.com/NemesisRE/kiosk-mode/blob/013b78390ecdf6ed027fed9a781019dd4ee2a001/.hass/config/configuration.yaml#L87-L89) but in my local I use storage mode

>btw, do you speak Dutch ??

Een beetje, wij kunnen over dieren pratten, kleuren and kinderen boeken, maar niet over Github en code 😅

**Comment by elchininet** [comment] 2023-12-14 22:15
When does this error occur?

> <img alt="Scherm­afbeelding 2023-12-14 om 23 12 30" width="1430" src="https://private-user-images.githubusercontent.com/33354141/290669784-39ba6db0-c9f8-4b5d-a89b-79db74a01db9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1OTIyOTMsIm5iZiI6MTcwMjU5MTk5MywicGF0aCI6Ii8zMzM1NDE0MS8yOTA2Njk3ODQtMzliYTZkYjAtYzlmOC00YjVkLWE4OWItNzlkYjc0YTAxZGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDIyMTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxOTQzNTg0ODY0ZmUwOGQ0ZjJiOWJmYTU5ZWVkYTE3YWRiYzlmNjBhMjZlY2E3NWFkMzE5MjFkNTJmNGNjNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fGA3jKeuVUlN3QB4AkHzCAZlbvQiSDMpf77GLGrcXbo">

**Comment by elchininet** [comment] 2023-12-14 23:08
I did some refactoring in #34.

With that change, if you change to another dashboard without a config and there is already a config in memory, this one is reused so it is not lost. Let‘s see if that fixes your issue. In the same pull request I added the `debug` parameter, if one enables it, it prints all the debug traces that we were testing here, useful to debug when some issue occurs.

**Comment by Mariusthvdb** [comment] 2023-12-15 09:10
ok now we have progress.
the filters seem to be applied like before, initial testing does hide them from view, also hides the dropbox if no attributes is left. I can cross all dashboards and views, and subviews. And all entities in dev tools state. so thats back to where we want it.

However, and thats the funny thing, if I check inspector this is printed:

<img width="361" alt="Scherm­afbeelding 2023-12-15 om 10 04 55" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/cc98f22e-0385-40c2-af78-440c2b1f9ee6">

which is really odd. still the empty list of filters. so where does it get them from, and why are they not printed....

**Comment by elchininet** [comment] 2023-12-15 09:44
It would be good to know why the config cannot be retrieved in some of your dashboards if you include it in every single one of them, but that is something that we can investigate in parallel.

I think that the change to get the config from memory if it cannot be retrieved from the dashboard makes sense in this kind of plugin because I would say that 95% of users will want to have the same configuration in all dashboards.

About the empty attributes in the debug message, that is normal, there should be some dialogs without filters or even without attributes. But if you say that it is printed with a dialog of an entity that has a match in the configuration and with attributes to show and still the plugin is removing the attributes correctly and still is printing a debug message with an empty array, that should not occur and it should be a bug in the debug messages logic.

**Comment by elchininet** [comment] 2023-12-15 09:49
About the "Object" printed in the console, that is something from Safari, just open the main object and you should be able to inspect the glob property.

**Comment by elchininet** [comment] 2023-12-15 09:53
Also try something on those empty arrays, try to open them, it could be that Safari is showing you that it is an array but it is not showing you what is inside but if you open them you force the dev tools to show you what has that array inside.

**Comment by Mariusthvdb** [comment] 2023-12-15 10:16
> But if you say that it is printed with a dialog of an entity that has a match in the configuration and with attributes to show and still the plugin is removing the attributes correctly and still is printing a debug message with an empty array, that should not occur and it should be a bug in the debug messages logic.

this exactly. check the bottom one on buienradar_temperature. It has an attribute that Ive configured to filter (in a glob), it does actually filter it, and still the list of filtered attributes is displayed as `[] (0)`

**Comment by elchininet** [comment] 2023-12-15 10:23
@Mariusthvdb 
Check with the last changes in `main`, I am printing the object as `JSON` during the debug messages just to avoid any weird issue with developer tools. Let me know if tou get the same result.

**Comment by Mariusthvdb** [comment] 2023-12-15 11:25
we can close this now? fixed in latest main with some accompanying instructions

**Comment by elchininet** [comment] 2023-12-15 11:47
>we can close this now? fixed in latest main with some accompanying instructions

Yes, I think that this is already solved, closing it 👍

**Closed by elchininet** 2023-12-15 11:47 UTC
